apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-vote-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-vote-front
  template:
    metadata:
      labels:
        app: azure-vote-front
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
        - name: azure-vote-front
          image: mcr.microsoft.com/azuredocs/azure-vote-front:v1
          volumeMounts:                               #code for DISK in app
            - mountPath: "/mnt/vol"                   #code for DISK in app
              name: mediavolume                       #code for DISK in app
          resources:
            requests:                                 #values of cpu and memory increase 2x because
              cpu: 200m                               #should be higher than the cache values
              memory: 256Mi                           #since it's the application and handles more requests?!
            limits:                                   #NOT SURE
              cpu: 500m
              memory: 512Mi
          ports:
            - containerPort: 80
          env:                                        #code for CACHE in app
            - name: REDIS                             #code for CACHE in app
              value: "azure-vote-back"                #code for CACHE in app
      volumes:                                        #code for DISK in app
        - name: mediavolume                           #code for DISK in app
          persistentVolumeClaim:                      #code for DISK in app
            claimName: azure-managed-disk             #code for DISK in app
---
apiVersion: v1
kind: Service
metadata:
  name: azure-vote-front
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: azure-vote-front
